// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
